/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listado paginado de agencias bancarias
         * @description Agencias activas con provincia, municipio y tipo (RF-CAT-006: filtros por provincia, municipio y tipo, búsqueda por nombre o código).
         */
        get: operations["agenciesIndex"];
        put?: never;
        /**
         * Crear una agencia bancaria
         * @description Crea una agencia (RF-CAT-003). El municipio debe pertenecer a la provincia declarada (RN-04); la incoherencia responde 422 sobre municipality_id.
         */
        post: operations["agenciesStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agencies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una agencia bancaria */
        get: operations["agenciesShow"];
        put?: never;
        post?: never;
        /**
         * Desactivar una agencia bancaria
         * @description Borrado lógico de la agencia (RF-CAT-001).
         */
        delete: operations["agenciesDestroy"];
        options?: never;
        head?: never;
        /**
         * Editar una agencia bancaria
         * @description Actualiza campos de una agencia (PATCH). El código es inmutable tras la creación; los cambios de ubicación revalidan RN-04.
         */
        patch: operations["agenciesUpdate"];
        trace?: never;
    };
    "/api/v1/catalogs/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listado paginado de un catálogo
         * @description Lista las entradas activas de un catálogo uniforme (RF-CAT-006: paginación, búsqueda por texto y orden por columnas clave). Tipos válidos: provinces, agency-types, organizations, entity-types, office-types, legal-basis-types, scientific-categories, educational-levels, occupational-categories, pension-types, beneficiary-types, races, positions, pension-regimes, payment-types, income-concepts.
         */
        get: operations["catalogsIndex"];
        put?: never;
        /**
         * Crear una entrada de catálogo
         * @description Crea una entrada de un catálogo uniforme (RF-CAT-001). El código es requerido cuando el catálogo lo tiene y es inmutable tras la creación. Las claves naturales duplicadas responden 422 con error por campo (RN-008).
         */
        post: operations["catalogsStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalogs/{type}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una entrada de catálogo */
        get: operations["catalogsShow"];
        put?: never;
        post?: never;
        /**
         * Desactivar una entrada de catálogo
         * @description Borrado lógico (RF-CAT-001): la entrada queda desactivada y excluida de los listados. Responde 409 mientras existan registros activos que la referencien.
         */
        delete: operations["catalogsDestroy"];
        options?: never;
        head?: never;
        /**
         * Editar una entrada de catálogo
         * @description Actualiza campos de una entrada (PATCH). El código es inmutable: enviar un código distinto responde 422 (RF-CAT-001).
         */
        patch: operations["catalogsUpdate"];
        trace?: never;
    };
    "/api/v1/catalogs/{type}/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaurar una entrada desactivada
         * @description Devuelve a la vida una entrada lógicamente desactivada (RF-AUD-004). La restauración es exclusiva del rol con permiso catalogs.manage (Administrador) y queda registrada en la bitácora con autor, fecha y valores restaurados.
         */
        post: operations["catalogRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/municipalities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listado paginado de municipios
         * @description Municipios activos con su provincia (RF-CAT-002). Filtrable por provincia y buscable por nombre o código (RF-CAT-006).
         */
        get: operations["municipalitiesIndex"];
        put?: never;
        /**
         * Crear un municipio
         * @description Crea un municipio (RF-CAT-002). El par código-provincia es único; el municipio especial Isla de la Juventud se crea con province_id null.
         */
        post: operations["municipalitiesStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/municipalities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un municipio */
        get: operations["municipalitiesShow"];
        put?: never;
        post?: never;
        /**
         * Desactivar un municipio
         * @description Borrado lógico del municipio (RF-CAT-001). Responde 409 mientras existan agencias activas que lo referencien.
         */
        delete: operations["municipalitiesDestroy"];
        options?: never;
        head?: never;
        /**
         * Editar un municipio
         * @description Actualiza campos de un municipio (PATCH). El código es inmutable tras la creación.
         */
        patch: operations["municipalitiesUpdate"];
        trace?: never;
    };
    "/api/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Búsqueda de personas
         * @description Búsqueda por identidad exacta, fragmentos de nombres/apellidos (combinables) y filtros básicos, paginada y ordenada por apellido/nombre/fecha de nacimiento (RF-PER-004). Los resultados incluyen fecha de nacimiento y padres para desambiguar homónimos.
         */
        get: operations["peopleIndex"];
        put?: never;
        /**
         * Registro de una persona
         * @description Alta con validación estructural del carné (RN-001) y control de duplicados (RF-PER-005): identidad ya registrada responde 409 con la persona registrada (también contra desactivadas); homónimos vivos responden 409 con los candidatos hasta que la petición lleve confirm=true. La ficha única de ciudadano es opcional y única.
         */
        post: operations["peopleStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle de una persona
         * @description Devuelve la persona activa con ese id (las desactivadas responden 404, RN-001: su identidad sigue reservada).
         */
        get: operations["peopleShow"];
        put?: never;
        post?: never;
        /**
         * Desactivación de una persona
         * @description Borrado lógico: la persona sale de búsquedas y detalle, pero su identidad queda reservada para siempre (RN-001) y el borrado queda auditado. La reactivación seguirá el patrón restore de ADR-19 cuando el módulo lo necesite.
         */
        delete: operations["peopleDestroy"];
        options?: never;
        head?: never;
        /**
         * Edición de una persona
         * @description Edición parcial con auditoría de valores previos (RF-PER-002). El carné de identidad es inmutable (RN-001) y la fecha de fallecimiento se registra por su propio endpoint: ambos campos responden 422 si viajan aquí.
         */
        patch: operations["peopleUpdate"];
        trace?: never;
    };
    "/api/v1/people/{id}/death": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registro de fallecimiento
         * @description Fija (o corrige) la fecha de fallecimiento (RF-PER-003): estrictamente posterior al nacimiento, nunca futura, datable y auditada con valores previos. Persona fallecida queda marcada como deceased en búsquedas y bloques para nuevos trámites.
         */
        post: operations["peopleRegisterDeath"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar la bitácora de acciones
         * @description Lista paginada y filtrable de la bitácora append-only (RF-AUD-003): filtros por usuario, sujeto, evento y rango de fechas. Requiere el permiso audit.view (rol Auditor o Administrador, sección 2.2).
         */
        get: operations["auditLogsIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar la bitácora a CSV
         * @description Exportación CSV de la bitácora con los mismos filtros del listado (RF-AUD-003), para el rol Auditor. Requiere el permiso audit.export.
         */
        get: operations["auditLogsExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autenticar credenciales y emitir token
         * @description Verifica las credenciales y emite un token Bearer (RF-SEG-001). El email desconocido y la contraseña errónea colapsan en el mismo 401 para no revelar cuál falló. Limitado por throttle: 10 intentos por minuto.
         */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usuario autenticado
         * @description Devuelve el usuario asociado al token Bearer de la solicitud (RF-SEG-001).
         */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revocar el token actual
         * @description Revoca el token Bearer usado en la solicitud y cierra la sesión (RF-SEG-001).
         */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/general-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listado paginado de las versiones de configuración
         * @description Lista las vigencias de la configuración general de la más reciente a la más antigua con su effective_to derivado (RF-CAT-005, RN-007).
         */
        get: operations["generalSettingsIndex"];
        put?: never;
        /**
         * Crear una nueva vigencia de la configuración
         * @description Crea una versión nueva e inmutable de los parámetros de cálculo con su fecha de entrada en vigor (RF-CAT-005). La fecha no puede coincidir con una vigencia existente (RN-007, sin solapamientos) y el por ciento máximo no puede ser menor que el base. No existe endpoint de edición: la corrección crea una versión nueva.
         */
        post: operations["generalSettingsStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/general-settings/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolver la configuración vigente
         * @description Acción de dominio RN-007: devuelve la versión con la mayor effective_from menor o igual a la fecha (hoy por el puerto Clock, o la indicada en `at`). 404 cuando ninguna versión está aún en vigor. Los cálculos de la Fase 3 congelarán la versión resuelta.
         */
        get: operations["generalSettingsCurrent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/general-settings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle de una versión
         * @description Devuelve una vigencia con su effective_to derivado. Las versiones históricas siempre se muestran (RF-CAT-005: la historia es reproducible).
         */
        get: operations["generalSettingsShow"];
        put?: never;
        post?: never;
        /**
         * Eliminar una vigencia no efectiva
         * @description Elimina una versión solo cuando todavía no ha entrado en vigor (effective_from en el futuro). Las versiones ya en vigor quedan protegidas para la reproducibilidad histórica de los cálculos (RN-007): responden 409. La FK de pension_cases.calculation_setting_id (Fase 3) reforzará esta regla en BD.
         */
        delete: operations["generalSettingsDestroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Agencia bancaria
         * @description Agencia bancaria con provincia, municipio y tipo (RF-CAT-003). La pareja municipio-provincia es coherente por construcción (RN-04).
         */
        Agency: {
            /**
             * Format: int64
             * @example 7
             */
            id?: number;
            /** @example BPA0101 */
            code?: string;
            /** @example Agencia 1 BPA Holguín */
            name?: string;
            type?: {
                /**
                 * Format: int64
                 * @example 1
                 */
                id?: number;
                /** @example AG */
                code?: string;
                /** @example Agencia */
                name?: string;
            };
            province?: {
                /**
                 * Format: int64
                 * @example 12
                 */
                id?: number;
                /** @example 12 */
                code?: string;
                /** @example Holguín */
                name?: string;
            };
            municipality?: {
                /**
                 * Format: int64
                 * @example 42
                 */
                id?: number;
                /** @example 07 */
                code?: string;
                /** @example Holguín */
                name?: string;
            };
            /** Format: date-time */
            deactivated_at?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        /**
         * Entrada de catálogo
         * @description Entrada de un catálogo uniforme servida por /api/v1/catalogs/{type}. Los campos opcionales dependen del catálogo.
         */
        CatalogItem: {
            /**
             * Format: int64
             * @example 1
             */
            id?: number;
            /**
             * @description Clave natural inmutable; presente solo en catálogos con código
             * @example EDAD
             */
            code?: string | null;
            /** @example Por edad */
            name?: string;
            /** @example Pensión por edad */
            description?: string | null;
            /**
             * @description Solo pension-regimes
             * @example 12
             */
            months_per_year?: number | null;
            /**
             * @description Solo income-concepts
             * @example true
             */
            applies_base_salary?: boolean | null;
            /**
             * Format: date-time
             * @description Borrado lógico (RF-CAT-001)
             */
            deactivated_at?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        /**
         * Municipio
         * @description Municipio cubano con su provincia (RF-CAT-002). province es null para el municipio especial Isla de la Juventud.
         */
        Municipality: {
            /**
             * Format: int64
             * @example 42
             */
            id?: number;
            /** @example 07 */
            code?: string;
            /** @example Holguín */
            name?: string;
            /** @description Provincia del municipio; null para el municipio especial */
            province?: {
                /**
                 * Format: int64
                 * @example 12
                 */
                id?: number;
                /** @example 12 */
                code?: string;
                /** @example Holguín */
                name?: string;
            } | null;
            /** Format: date-time */
            deactivated_at?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        /**
         * Persona
         * @description Persona del registro único del SGP (RF-PER-001). deceased se deriva de death_date: el fallecimiento es una fecha, estar fallecido es estado derivado, nunca una columna.
         */
        Person: {
            /**
             * Format: int64
             * @description Person projection (RF-PER-001..004). It carries the fields the
             *     search needs to disambiguate homonyms (identity, birth date and
             *     parents) plus the derived deceased flag: death is a date, "being
             *      * deceased" is derived state, never a column (model data 5.4).
             * @example 1
             */
            id?: number;
            /**
             * @description Carné de identidad: 11 dígitos, único e inmutable (RN-001)
             * @example 18506150012
             */
            identity_number?: string;
            /**
             * @description Primer nombre
             * @example Juan
             */
            first_name?: string;
            /**
             * @description Segundo nombre
             * @example Carlos
             */
            middle_name?: string | null;
            /**
             * @description Primer apellido
             * @example Pérez
             */
            first_surname?: string;
            /**
             * @description Segundo apellido
             * @example Gómez
             */
            second_surname?: string | null;
            /**
             * @description Sexo (CHECK de BD)
             * @example M
             * @enum {string}
             */
            sex?: "M" | "F";
            /**
             * Format: int64
             * @description Raza declarada (catálogo)
             * @example 3
             */
            race_id?: number | null;
            /** @example Calle 23 #45, Vedado, La Habana */
            address?: string;
            /**
             * Format: date
             * @example 1985-06-15
             */
            birth_date?: string;
            /**
             * Format: date
             * @description Fecha de fallecimiento (RF-PER-003); null mientras viva
             * @example null
             */
            death_date?: string | null;
            /**
             * @description Desambiguación de homónimos (RF-PER-004)
             * @example Pedro Pérez Rodríguez
             */
            father_name?: string | null;
            /**
             * @description Desambiguación de homónimos (RF-PER-004)
             * @example María Gómez Fernández
             */
            mother_name?: string | null;
            /**
             * @description Ficha única de ciudadano, opcional y única (RF-PER-005)
             * @example null
             */
            citizen_card_id?: string | null;
            /**
             * @description Derivado: death_date no nula
             * @example false
             */
            deceased?: boolean;
        };
        /**
         * Entrada de bitácora
         * @description Registro append-only de una escritura crítica: autor, sujeto, valores previos y nuevos, y contexto de la solicitud (RF-AUD-001).
         */
        AuditLogEntry: {
            /**
             * Format: int64
             * @example 42
             */
            id?: number;
            /**
             * @example updated
             * @enum {string}
             */
            event?: "created" | "updated" | "deleted" | "restored";
            /** @example updated */
            description?: string;
            /**
             * Format: int64
             * @example 1
             */
            causer_id?: number | null;
            /** @example App\Modules\Catalogs\Infrastructure\Persistence\Models\Race */
            subject_type?: string | null;
            /**
             * Format: int64
             * @example 3
             */
            subject_id?: number | null;
            /**
             * @description Valores previos de los atributos modificados (nulo en created/restored)
             * @example {"name": "Otra"}
             */
            old?: Record<string, never> | null;
            /**
             * @description Valores nuevos de los atributos modificados (nulo en deleted)
             * @example {"name": "Otra raza"}
             */
            changes?: Record<string, never> | null;
            /** @example 9d5b1c2e-6f4a-4c1e-8f3b-2a7d9e0c5b41 */
            request_id?: string | null;
            /**
             * Format: date-time
             * @example 2026-09-27T12:00:00.000000Z
             */
            created_at?: string;
        };
        /**
         * Usuario
         * @description Usuario del sistema SGP con sus roles y permisos efectivos (RF-SEG-002).
         */
        User: {
            /**
             * Format: int64
             * @example 1
             */
            id?: number;
            /** @example SGP Demo Admin */
            name?: string;
            /**
             * Format: email
             * @example admin@sgp.local
             */
            email?: string;
            /** @description Roles institucionales asignados (sección 2.2) */
            roles?: string[];
            /** @description Permisos efectivos (de roles y directos), orden alfabético */
            permissions?: string[];
        };
        /**
         * Versión de configuración general
         * @description Parámetros de cálculo de una vigencia (RF-CAT-005, RN-007). Las versiones son inmutables: la corrección crea una nueva vigencia. effective_to es derivado (día anterior a la siguiente vigencia; null en la más reciente) y nunca se almacena.
         */
        GeneralSettingVersion: {
            /**
             * Format: int64
             * @example 3
             */
            id?: number;
            /**
             * @description Años mínimos de trabajo
             * @example 30
             */
            min_work_years?: number;
            /**
             * @description Edad mínima hombres
             * @example 60
             */
            min_age_men?: number;
            /**
             * @description Edad mínima mujeres
             * @example 55
             */
            min_age_women?: number;
            /**
             * @description Por ciento de cálculo base
             * @example 50
             */
            base_calc_percent?: number;
            /**
             * @description Por ciento máximo (mayor o igual que base)
             * @example 90
             */
            max_calc_percent?: number;
            /**
             * @description Incremento anual por excedencia
             * @example 1
             */
            annual_increase_percent?: number;
            /**
             * Format: date
             * @description Entrada en vigor (única por fecha, RN-007)
             * @example 2026-06-01
             */
            effective_from?: string;
            /**
             * Format: date
             * @description Derivado: día anterior a la siguiente vigencia; null en la vigencia más reciente
             * @example null
             */
            effective_to?: string | null;
            /**
             * Format: int64
             * @description Usuario autor de la versión (ADR-14)
             */
            created_by?: number | null;
            /** Format: date-time */
            created_at?: string | null;
        };
    };
    responses: {
        /** @description Token ausente, inválido o revocado */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /**
                     * @description Reusable OpenAPI response components (ADR-13).
                     *
                     *     Centralizes the cross-cutting error shapes of the SGP API so every
                     *     protected operation references the same component instead of
                     *     duplicating inline definitions: 401 for the Sanctum bearer scheme,
                     *     403 for the RBAC permission guard (RF-SEG-002, ADR-18) and 422 for
                     *     the per-field validation envelope (RF-API-002).
                     * @example Unauthenticated.
                     */
                    message?: string;
                };
            };
        };
        /** @description Sin el permiso requerido para la operación (RF-SEG-002) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Forbidden. */
                    message?: string;
                };
            };
        };
        /** @description Payload inválido o regla de negocio incumplida (errores por campo) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example The code is already in use. */
                    message?: string;
                    errors?: {
                        code?: string[];
                    };
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agenciesIndex: {
        parameters: {
            query?: {
                province_id?: number | null;
                municipality_id?: number | null;
                agency_type_id?: number | null;
                search?: string;
                sort?: "name" | "code" | "id";
                order?: "asc" | "desc";
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado con envelope RF-API-002 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Agency"][];
                        meta?: {
                            /** @example 1 */
                            current_page?: number;
                            /** @example 15 */
                            per_page?: number;
                            /** @example 25 */
                            total?: number;
                            /** @example 2 */
                            last_page?: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    agenciesStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example BPA1207 */
                    code: string;
                    /** @example Agencia Holguín BPA */
                    name: string;
                    /** @example 12 */
                    province_id: number;
                    /** @example 42 */
                    municipality_id: number;
                    /** @example 1 */
                    agency_type_id: number;
                };
            };
        };
        responses: {
            /** @description Agencia creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Agency"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    agenciesShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agencia solicitada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Agency"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Agencia inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Agency not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    agenciesDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agencia desactivada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Agency deactivated. */
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Agencia inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Agency not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    agenciesUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    province_id?: number;
                    municipality_id?: number;
                    agency_type_id?: number;
                };
            };
        };
        responses: {
            /** @description Agencia actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Agency"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Agencia inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Agency not found. */
                        message?: string;
                    };
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    catalogsIndex: {
        parameters: {
            query?: {
                /** @description Filtro por nombre (y código cuando el catálogo lo tiene) */
                search?: string;
                /** @description Columna de orden */
                sort?: "name" | "code" | "id";
                order?: "asc" | "desc";
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                /** @description Clave del catálogo */
                type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado con envelope RF-API-002 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CatalogItem"][];
                        meta?: {
                            /** @example 1 */
                            current_page?: number;
                            /** @example 15 */
                            per_page?: number;
                            /** @example 3 */
                            total?: number;
                            /** @example 1 */
                            last_page?: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Catálogo desconocido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unknown catalog. */
                        message?: string;
                    };
                };
            };
        };
    };
    catalogsStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        /** @description Campos de la entrada; los opcionales dependen del catálogo */
        requestBody: {
            content: {
                "application/json": {
                    /** @example GEN */
                    code?: string;
                    /** @example General */
                    name: string;
                    /** @example Régimen general de 12 meses por año */
                    description?: string | null;
                    /** @example 12 */
                    months_per_year?: number;
                    /** @example true */
                    applies_base_salary?: boolean;
                };
            };
        };
        responses: {
            /** @description Entrada creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CatalogItem"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Catálogo desconocido */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unknown catalog. */
                        message?: string;
                    };
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    catalogsShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entrada solicitada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CatalogItem"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Catálogo desconocido o entrada inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Not Found */
                        message?: string;
                    };
                };
            };
        };
    };
    catalogsDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entrada desactivada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Catalog entry deactivated. */
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Catálogo desconocido o entrada inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Not Found */
                        message?: string;
                    };
                };
            };
            /** @description Existen referencias activas que bloquean la desactivación */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The catalog entry cannot be deactivated while active records reference it. */
                        message?: string;
                    };
                };
            };
        };
    };
    catalogsUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
                id: number;
            };
            cookie?: never;
        };
        /** @description Campos a actualizar (semántica PATCH) */
        requestBody: {
            content: {
                "application/json": {
                    /** @example Por edad (actualizado) */
                    name?: string;
                    description?: string | null;
                    months_per_year?: number;
                    applies_base_salary?: boolean;
                };
            };
        };
        responses: {
            /** @description Entrada actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CatalogItem"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Catálogo desconocido o entrada inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Not Found */
                        message?: string;
                    };
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    catalogRestore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entrada restaurada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Catalog entry restored. */
                        message?: string;
                    };
                };
            };
            /** @description Sin permiso catalogs.manage */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Forbidden. */
                        message?: string;
                    };
                };
            };
            /** @description Catálogo desconocido o entrada inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Not Found */
                        message?: string;
                    };
                };
            };
            /** @description La entrada ya está activa */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The catalog entry is already active: only deactivated entries can be restored. */
                        message?: string;
                    };
                };
            };
        };
    };
    municipalitiesIndex: {
        parameters: {
            query?: {
                /** @description Filtra por provincia */
                province_id?: number | null;
                search?: string;
                sort?: "name" | "code" | "id";
                order?: "asc" | "desc";
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado con envelope RF-API-002 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Municipality"][];
                        meta?: {
                            /** @example 1 */
                            current_page?: number;
                            /** @example 15 */
                            per_page?: number;
                            /** @example 168 */
                            total?: number;
                            /** @example 12 */
                            last_page?: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    municipalitiesStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 12 */
                    province_id?: number | null;
                    /** @example 99 */
                    code: string;
                    /** @example Nueva Paz */
                    name: string;
                };
            };
        };
        responses: {
            /** @description Municipio creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Municipality"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    municipalitiesShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Municipio solicitado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Municipality"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Municipio inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Municipality not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    municipalitiesDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Municipio desactivado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Municipality deactivated. */
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Municipio inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Municipality not found. */
                        message?: string;
                    };
                };
            };
            /** @description Existen agencias activas que referencian el municipio */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The catalog entry cannot be deactivated while active records reference it: agencies. */
                        message?: string;
                    };
                };
            };
        };
    };
    municipalitiesUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    province_id?: number | null;
                    /** @example Nueva Paz (renamed) */
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Municipio actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Municipality"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Municipio inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Municipality not found. */
                        message?: string;
                    };
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    peopleIndex: {
        parameters: {
            query?: {
                /** @description Número de identidad exacto */
                identity?: string;
                /** @description Fragmentos de nombre/apellido (cada palabra debe aparecer) */
                q?: string;
                sex?: "M" | "F";
                deceased?: boolean;
                /** @description Nacidos desde (Y-m-d, inclusivo) */
                birth_from?: string;
                /** @description Nacidos hasta (Y-m-d, inclusivo) */
                birth_to?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultados paginados con envelope RF-API-002 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Person"][];
                        meta?: {
                            /** @example 1 */
                            current_page?: number;
                            /** @example 15 */
                            per_page?: number;
                            /** @example 42 */
                            total?: number;
                            /** @example 3 */
                            last_page?: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    peopleStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 18506150012 */
                    identity_number: string;
                    /** @example Juan */
                    first_name: string;
                    /** @example Carlos */
                    middle_name?: string | null;
                    /** @example Pérez */
                    first_surname: string;
                    /** @example Gómez */
                    second_surname?: string | null;
                    /**
                     * @example M
                     * @enum {string}
                     */
                    sex: "M" | "F";
                    /** @example 3 */
                    race_id?: number | null;
                    /** @example Calle 23 #45, Vedado, La Habana */
                    address: string;
                    /**
                     * Format: date
                     * @example 1985-06-15
                     */
                    birth_date: string;
                    father_name?: string | null;
                    mother_name?: string | null;
                    citizen_card_id?: string | null;
                    /**
                     * @description Confirmación del aviso de homónimos (RF-PER-005)
                     * @example false
                     */
                    confirm?: boolean | null;
                };
            };
        };
        responses: {
            /** @description Persona registrada con autoría estampada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Person"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Duplicado: identity_number ya registrada (devuelve la persona) u homónimos vivos (devuelve candidatos) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                        person?: components["schemas"]["Person"] | null;
                        candidates?: {
                            id?: number;
                            identity_number?: string;
                            first_name?: string;
                            first_surname?: string;
                            birth_date?: string;
                        }[] | null;
                    };
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    peopleShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persona */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Person"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Persona inexistente o desactivada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    peopleDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persona desactivada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Person deactivated. */
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Persona inexistente o ya desactivada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    peopleUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example Juan */
                    first_name?: string;
                    middle_name?: string | null;
                    /** @example Pérez */
                    first_surname?: string;
                    second_surname?: string | null;
                    /** @enum {string} */
                    sex?: "M" | "F";
                    race_id?: number | null;
                    /** @example Calle 5 #12, Vedado, La Habana */
                    address?: string;
                    /** Format: date */
                    birth_date?: string;
                    father_name?: string | null;
                    mother_name?: string | null;
                    citizen_card_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Persona actualizada (valores previos en la bitácora) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Person"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Persona inexistente o desactivada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    peopleRegisterDeath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: date
                     * @example 2024-03-10
                     */
                    death_date: string;
                };
            };
        };
        responses: {
            /** @description Fallecimiento registrado (o corregido) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Person"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Persona inexistente o desactivada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationError"];
        };
    };
    auditLogsIndex: {
        parameters: {
            query?: {
                /** @description Filtro por usuario autor */
                causer_id?: number;
                /** @description Filtro por clase del sujeto */
                subject_type?: string;
                /** @description Filtro por id del sujeto */
                subject_id?: number;
                event?: "created" | "updated" | "deleted" | "restored";
                /** @description Límite inferior inclusive (Y-m-d) */
                from?: string;
                /** @description Límite superior inclusive (Y-m-d) */
                to?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entradas de bitácora paginadas (envoltura RF-API-002) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuditLogEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    auditLogsExport: {
        parameters: {
            query?: {
                causer_id?: number;
                subject_type?: string;
                subject_id?: number;
                event?: "created" | "updated" | "deleted" | "restored";
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archivo CSV con las entradas filtradas (máximo 10 000 filas) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Credenciales del usuario */
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example admin@sgp.local
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example password
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Sesión iniciada: envelope RF-API-002 con token y usuario */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            /** @example 1|9QsTjXxaYl2nW8kJ */
                            token?: string;
                            /** @example Bearer */
                            token_type?: string;
                            user?: components["schemas"]["User"];
                        };
                    };
                };
            };
            /** @description Credenciales inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Invalid credentials. */
                        message?: string;
                    };
                };
            };
            /** @description Payload inválido (campos requeridos o con formato incorrecto) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The email field is required. */
                        message?: string;
                        errors?: {
                            email?: string[];
                        };
                    };
                };
            };
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuario autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["User"];
                    };
                };
            };
            /** @description Token ausente, inválido o revocado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthenticated. */
                        message?: string;
                    };
                };
            };
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revocado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Token revoked. */
                        message?: string;
                    };
                };
            };
            /** @description Token ausente, inválido o ya revocado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthenticated. */
                        message?: string;
                    };
                };
            };
        };
    };
    generalSettingsIndex: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado con envelope RF-API-002 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GeneralSettingVersion"][];
                        meta?: {
                            /** @example 1 */
                            current_page?: number;
                            /** @example 15 */
                            per_page?: number;
                            /** @example 3 */
                            total?: number;
                            /** @example 1 */
                            last_page?: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    generalSettingsStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 30 */
                    min_work_years: number;
                    /** @example 60 */
                    min_age_men: number;
                    /** @example 55 */
                    min_age_women: number;
                    /** @example 50 */
                    base_calc_percent: number;
                    /** @example 90 */
                    max_calc_percent: number;
                    /** @example 1 */
                    annual_increase_percent: number;
                    /**
                     * Format: date
                     * @example 2027-01-01
                     */
                    effective_from: string;
                };
            };
        };
        responses: {
            /** @description Vigencia creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GeneralSettingVersion"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    generalSettingsCurrent: {
        parameters: {
            query?: {
                /** @description Fecha de resolución opcional (Y-m-d) */
                at?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versión en vigor a la fecha */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GeneralSettingVersion"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Ninguna versión en vigor a la fecha */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example No general settings are in effect at the given date. */
                        message?: string;
                    };
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    generalSettingsShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versión encontrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GeneralSettingVersion"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Versión inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Not found. */
                        message?: string;
                    };
                };
            };
        };
    };
    generalSettingsDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vigencia futura eliminada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Future settings version deleted. */
                        message?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Versión inexistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Not found. */
                        message?: string;
                    };
                };
            };
            /** @description La versión ya está en vigor y no puede eliminarse */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example The version effective from 2026-06-01 is already in effect and cannot be deleted. */
                        message?: string;
                    };
                };
            };
        };
    };
}
